### ISSUE TITLE
Feature Request: Dynamically update constants

### ISSUE THREAD

**Issue by BenJamesAndo** [umanamente/n8n-nodes-globals#2]
Hello, thank you for creating this node.
I might be missing something, but is it possible to use a workflow to update a value of a constant? I know you can insert expressions into the Connection - Global Constants, but then in a second workflow it would be looking for the expression and not work properly.

Basically I want to use workflow 1 to update a constant and then have workflow 2 reference it and potentially update it to something else at the end. Currently it seems that I'm meant to manually set some values and just use them for static referencing.

Perhaps under Put All Constants in One Key there could be another option to set value of line 1 constant, line 2 constant etc.

**Comment by umanamente** [comment]
@BenJamesAndo unfortunately it's not possible to change the constants within workflows in current implementation. Consider using external datastore, or using static data.

**Comment by BenJamesAndo** [comment]
For anyone reading this later, I found another community node that does allow you to create and edit locally stored variables between executions or different workflows. https://github.com/telepilotco/n8n-nodes-kv-storage
