### ISSUE TITLE
Missing option to add credential.

### ISSUE THREAD

**Issue by danielbowne** [umanamente/n8n-nodes-globals#3]
Not listed in the options to add as a credential either.  I am on self hosted, newest version 1.42.1
![image](https://github.com/umanamente/n8n-nodes-globals/assets/17046382/574044e0-91cb-476f-ad62-6497576f0eef)

**Comment by umanamente** [comment]
Please reach out to N8N support, they might help diagnose the problem (there might be something wrong with your n8n setup). 
This is a strange problem, and it might indicate something is wrong with the n8n configuration.
Additionally, try restarting your n8n service.

**Comment by haritac** [comment]
Same problem ... any solution?

**Comment by Slopz** [comment]
Same here

**Comment by digital-soul18** [comment]
Same problem here

**Comment by umanamente** [comment]
Please reach out to N8N support, they might help diagnose the problem (there might be something wrong with your n8n setup).

**Comment by umanamente** [comment]
This is a known issue. Clearing browser cache might help.

Check https://community.n8n.io/t/community-nodes-not-accessable/46347
