### ISSUE TITLE
Install Question

### ISSUE THREAD

**Issue by hugorn** [umanamente/n8n-nodes-globals#4]
I tried to install it on my server but the icon did not display on the interface, follow the installation process step by step.

docker ps
c9255233f355 n8n-setup-n8n "tini -- /docker-ent…" 14 minutes ago Up 10 minutes 0.0.0.0:80->5678/tcp, :::80->5678/tcp
docker exec -it c9255233f355 sh
mkdir -p ~/.n8n/nodes
cd ~/.n8n/nodes
npm i n8n-nodes-globals

After that I restarted the container but I was unable to locate the node in the interface

![image](https://github.com/umanamente/n8n-nodes-globals/assets/9035153/a52e37b1-c990-46b5-b746-3349b8bbb699)

n8n Version1.45.1

**Comment by umanamente** [comment]
Please reach out to N8N support, they might help diagnose the problem.
