### ISSUE TITLE
More "Usage" examples, please.

### ISSUE THREAD

**Issue by MadOtis** [umanamente/n8n-nodes-globals#8]
Can you add some additional docs on how to use those new Global Constants in real-life events other than how they display in a flow?  For example, when adding an HTTP Get call to a flow, can those constants pre-defined in the node be used as variables within a URL?  for example:  https://my.api.fqdn/foo/CONSTANT/data. <-- replacing the word CONSTANT with the value of a key defined in the constants node previously.

Or, add an additional doc note on how to use one of those constants in something like an HTTP Get header value?

I'll caveat that I'm new to writing N8N flows on a self-hosted personal instance and might be missing something obvious about how those values that get defined in the Global Constants node are actually used later in flows.

**Comment by umanamente** [comment]
The functionality you're asking about is part of N8N’s core system through its expression engine. You can dynamically set node parameters using expressions, which can combine multiple parameters or even custom JavaScript. This is not related specifically to any custom node.

In your case, to include a constant or any dynamic value in an HTTP GET URL or header, you would use N8N's expression editor. The editor allows you to pull data from previous nodes or other workflow variables. You can reference values from any node and even use JavaScript functions directly in the expressions to achieve the desired result. For example, you could build the URL dynamically like this:

``https://my.api.fqdn/foo/{{$json["constant"]}}/data``

For more details on how to use expressions and their capabilities, including data transformations, check out the [N8N documentation on expressions](https://docs.n8n.io/code-examples/expression-examples/). If you still have questions, feel free to post them on the N8N community forum.

**Comment by MadOtis** [comment]
Awesome!  And thanks for the super-quick reply.  I AM still learning this amazing new tool, so thanks for the tip and location to start researching!
